travis:
  secure:
    BINSTAR_TOKEN: GC4Be21q3ewrUDc7B191MakXnQ1tlTAU0VD7Fn8WS17IVY50zOvIVpGwbwKjRfxDb6j1z+ZHeZTEH9X4MxAXXjkAscoWszu2mnUclGrYiTWP1fG0GpabQ+yV8Uifw7qV1JwbuMGngj+MtpQ1z1lqHqNcrXETiqEFPVqx2v6n/QBbsWnD39GO/VWRgO6OOn6pkKo9iAJyvQXpULtWRW5AbsWejGAC+Wag1C7eOZllfLl2lUtVAY9wz9YsAJPDtcOTtadDYmoX+YqlPCZm9kLSBzD9JuLq+NQIj5UcuZSDA0f9X0/H3ENfqnGuoIbu6QbvFTyCFzEdq95CosoHAn8Q79vTVDEUJbko8mIJRRnqfB+kSYGZwlxVrEFWZ1iCPfRWXrbI3ngzgWGFN/+jppmmQ1QfYG7R3FVp5H4DLgBijsNdqYycIeA7+X+zo9uyhpSl3c1o9ae79+CbjzYf6uGxTzCVeYjFXFMQDeQZTcb6759qfTuz0r70bxgtzTpUU0YhP75XR7daV/K3m41y/M98zNkw4jXE1lgCouMtwZz/fsDEcvkZganL96yWjhzc6gpDbmbSAiOOFBdYkP78XR/sj+4iz0UxiUFnIEIIF06gRZZ3revHYtBL5fLkjJ62NP0RF8/huhg2/UYCuznllhiT3wDKUslMRsSv4whbAvL9suU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
